In [1]:
import pandas as pd
import numpy as np

df = pd.read_excel("Min_macros_for_height_and_weight.xlsx")

In [2]:
df

,Unnamed: 0,Height,Weight,bmi,bmi_range,Protein (grams/day),Carbs (grams/day),Fat (grams/day),Sugar (grams/day),Saturated Fat (grams/day),Food Energy (Calories/day)
0,0,177.74,74.74,23.66,Normal,146.0,319.0,68.0,64.0,27.0,"2,390"
1,1,149.72,38.52,17.18,Underweight,101.0,220.0,47.0,44.0,19.0,"1,651"
2,2,142.78,45.87,22.50,Normal,103.0,226.0,48.0,45.0,19.0,"1,693"
3,3,160.85,61.73,23.86,Normal,126.0,275.0,59.0,55.0,23.0,"2,066"
4,4,182.25,105.28,31.70,Obesity,174.0,380.0,81.0,76.0,32.0,"2,849"
...,...,...,...,...,...,...,...,...,...,...,...
95,95,147.82,45.29,20.73,Normal,105.0,230.0,49.0,46.0,20.0,"1,728"
96,96,180.27,103.48,31.84,Obesity,171.0,374.0,80.0,75.0,32.0,"2,807"
97,97,183.51,107.12,31.81,Obesity,176.0,385.0,82.0,77.0,33.0,"2,885"
98,98,164.39,85.51,31.64,Obesity,148.0,323.0,69.0,65.0,28.0,"2,423"
99,99,179.51,95.86,29.75,Overweight,164.0,359.0,77.0,72.0,31.0,"2,696"

In [3]:
df['Food Energy (Calories/day)'] = df['Food Energy (Calories/day)'].str.replace(',', '').astype(float)

np.random.seed(42)  

df['Age'] = np.random.randint(18, 61, size=len(df))
df['Gender'] = np.random.choice(['Male', 'Female'], size=len(df))
df['Activity Level'] = np.random.choice(['Sedentary', 'Lightly active', 'Moderately active', 'Very active'], size=len(df))
df['Goal'] = np.random.choice(['Lose', 'Gain', 'Maintain'], size=len(df))
df['Days'] = np.random.randint(30, 121, size=len(df))

In [4]:
print(df[['Height', 'Weight', 'Age', 'Gender', 'Activity Level', 'Goal', 'Days']].head())

   Height  Weight  Age  Gender     Activity Level      Goal  Days
0  177.74   74.74   56    Male          Sedentary      Lose    54
1  149.72   38.52   46    Male     Lightly active      Lose    83
2  142.78   45.87   32  Female          Sedentary      Gain    87
3  160.85   61.73   60  Female          Sedentary  Maintain    96
4  182.25  105.28   25  Female  Moderately active  Maintain    75

In [5]:
df

,Unnamed: 0,Height,Weight,bmi,bmi_range,Protein (grams/day),Carbs (grams/day),Fat (grams/day),Sugar (grams/day),Saturated Fat (grams/day),Food Energy (Calories/day),Age,Gender,Activity Level,Goal,Days
0,0,177.74,74.74,23.66,Normal,146.0,319.0,68.0,64.0,27.0,2390.0,56,Male,Sedentary,Lose,54
1,1,149.72,38.52,17.18,Underweight,101.0,220.0,47.0,44.0,19.0,1651.0,46,Male,Lightly active,Lose,83
2,2,142.78,45.87,22.50,Normal,103.0,226.0,48.0,45.0,19.0,1693.0,32,Female,Sedentary,Gain,87
3,3,160.85,61.73,23.86,Normal,126.0,275.0,59.0,55.0,23.0,2066.0,60,Female,Sedentary,Maintain,96
4,4,182.25,105.28,31.70,Obesity,174.0,380.0,81.0,76.0,32.0,2849.0,25,Female,Moderately active,Maintain,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95,147.82,45.29,20.73,Normal,105.0,230.0,49.0,46.0,20.0,1728.0,22,Male,Moderately active,Lose,92
96,96,180.27,103.48,31.84,Obesity,171.0,374.0,80.0,75.0,32.0,2807.0,59,Male,Lightly active,Maintain,98
97,97,183.51,107.12,31.81,Obesity,176.0,385.0,82.0,77.0,33.0,2885.0,56,Female,Very active,Lose,51
98,98,164.39,85.51,31.64,Obesity,148.0,323.0,69.0,65.0,28.0,2423.0,58,Female,Sedentary,Maintain,96
99,99,179.51,95.86,29.75,Overweight,164.0,359.0,77.0,72.0,31.0,2696.0,45,Male,Moderately active,Gain,105

In [7]:
df.columns

Index(['Unnamed: 0', 'Height', 'Weight', 'bmi', 'bmi_range',
       'Protein (grams/day)', 'Carbs (grams/day)', 'Fat (grams/day)',
       'Sugar (grams/day)', 'Saturated Fat (grams/day)',
       'Food Energy (Calories/day)', 'Age', 'Gender', 'Activity Level', 'Goal',
       'Days'],
      dtype='object')

In [10]:
df = df.drop(['Unnamed: 0'], axis=1)

In [11]:
print(df.columns)

Index(['Height', 'Weight', 'bmi', 'bmi_range', 'Protein (grams/day)',
       'Carbs (grams/day)', 'Fat (grams/day)', 'Sugar (grams/day)',
       'Saturated Fat (grams/day)', 'Food Energy (Calories/day)', 'Age',
       'Gender', 'Activity Level', 'Goal', 'Days'],
      dtype='object')

In [12]:
df

,Height,Weight,bmi,bmi_range,Protein (grams/day),Carbs (grams/day),Fat (grams/day),Sugar (grams/day),Saturated Fat (grams/day),Food Energy (Calories/day),Age,Gender,Activity Level,Goal,Days
0,177.74,74.74,23.66,Normal,146.0,319.0,68.0,64.0,27.0,2390.0,56,Male,Sedentary,Lose,54
1,149.72,38.52,17.18,Underweight,101.0,220.0,47.0,44.0,19.0,1651.0,46,Male,Lightly active,Lose,83
2,142.78,45.87,22.50,Normal,103.0,226.0,48.0,45.0,19.0,1693.0,32,Female,Sedentary,Gain,87
3,160.85,61.73,23.86,Normal,126.0,275.0,59.0,55.0,23.0,2066.0,60,Female,Sedentary,Maintain,96
4,182.25,105.28,31.70,Obesity,174.0,380.0,81.0,76.0,32.0,2849.0,25,Female,Moderately active,Maintain,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,147.82,45.29,20.73,Normal,105.0,230.0,49.0,46.0,20.0,1728.0,22,Male,Moderately active,Lose,92
96,180.27,103.48,31.84,Obesity,171.0,374.0,80.0,75.0,32.0,2807.0,59,Male,Lightly active,Maintain,98
97,183.51,107.12,31.81,Obesity,176.0,385.0,82.0,77.0,33.0,2885.0,56,Female,Very active,Lose,51
98,164.39,85.51,31.64,Obesity,148.0,323.0,69.0,65.0,28.0,2423.0,58,Female,Sedentary,Maintain,96
99,179.51,95.86,29.75,Overweight,164.0,359.0,77.0,72.0,31.0,2696.0,45,Male,Moderately active,Gain,105

In [13]:
activity_multipliers = {
    'Sedentary': 1.2,
    'Lightly active': 1.375,
    'Moderately active': 1.55,
    'Very active': 1.725
}

def calculate_bmr(row):
    weight = row['Weight']
    height = row['Height']
    age = row['Age']
    gender = row['Gender']
    
    if gender == 'Male':
        return 10 * weight + 6.25 * height - 5 * age + 5
    else:
        return 10 * weight + 6.25 * height - 5 * age - 161

In [14]:
df['BMR'] = df.apply(calculate_bmr, axis=1)
df['TDEE'] = df['BMR'] * df['Activity Level'].map(activity_multipliers)

In [15]:
def calculate_target_calories(row):
    if row['Goal'] == 'Lose':
        return row['TDEE'] - 500
    elif row['Goal'] == 'Gain':
        return row['TDEE'] + 500
    else:
        return row['TDEE']

df['Target Calories'] = df.apply(calculate_target_calories, axis=1)

In [16]:
df[['Age', 'Gender', 'Activity Level', 'Goal', 'BMR', 'TDEE', 'Target Calories']].head()

,Age,Gender,Activity Level,Goal,BMR,TDEE,Target Calories
0,56,Male,Sedentary,Lose,1583.2750,1899.930000,1399.930000
1,46,Male,Lightly active,Lose,1095.9500,1506.931250,1006.931250
2,32,Female,Sedentary,Gain,1030.0750,1236.090000,1736.090000
3,60,Female,Sedentary,Maintain,1161.6125,1393.935000,1393.935000
4,25,Female,Moderately active,Maintain,1905.8625,2954.086875,2954.086875

In [17]:
# Calculate macro calories
df['Protein Calories'] = df['Target Calories'] * 0.25
df['Carb Calories']    = df['Target Calories'] * 0.45
df['Fat Calories']     = df['Target Calories'] * 0.30

# Convert calories to grams
df['Protein (g)'] = df['Protein Calories'] / 4
df['Carbs (g)']   = df['Carb Calories'] / 4
df['Fats (g)']    = df['Fat Calories'] / 9

# Round for cleaner display
df[['Protein (g)', 'Carbs (g)', 'Fats (g)']] = df[['Protein (g)', 'Carbs (g)', 'Fats (g)']].round(1)

In [18]:
df[['Target Calories', 'Protein (g)', 'Carbs (g)', 'Fats (g)']].head()

   Target Calories  Protein (g)  Carbs (g)  Fats (g)
0      1399.930000         87.5      157.5      46.7
1      1006.931250         62.9      113.3      33.6
2      1736.090000        108.5      195.3      57.9
3      1393.935000         87.1      156.8      46.5
4      2954.086875        184.6      332.3      98.5

In [19]:
df.to_csv("enriched_diet_dataset.csv", index=False)